import streamlit as st

from utils.ui import render_professional_sidebar


st.set_page_config(page_title="Introduction", layout="wide")
render_professional_sidebar("Introduction")

st.title("Introduction")
st.subheader("Statistical Deepfake Detection in Images")

st.markdown(
    """
Deepfakes are synthetic images or videos generated by AI models that imitate real-world visual
content. While they can be useful for creativity and simulation, they can also be used for
misinformation, identity abuse, and manipulation.
"""
)

col1, col2 = st.columns(2)

with col1:
    st.markdown("### What are deepfakes?")
    st.write(
        "Deepfakes are media generated or altered with machine learning systems such as GANs, "
        "diffusion models, and transformer-based generators."
    )

    st.markdown("### Why detection matters")
    st.write(
        "Reliable detection is essential for digital forensics, media trust, legal evidence, and "
        "online safety."
    )

    st.markdown("### Risks of synthetic media")
    st.write(
        "Potential harms include social engineering, reputation damage, political disinformation, "
        "and fraud."
    )

with col2:
    st.markdown("### Why statistical detection?")
    st.write(
        "This thesis studies measurable image properties (noise, texture, frequency, intensity) "
        "to detect inconsistencies that may signal synthetic generation."
    )
    st.info(
        "Statistical methods are interpretable and lightweight, making them useful as forensic "
        "support tools and complements to deep models."
    )

st.markdown("### Deepfake generation architecture families")
st.graphviz_chart(
    """
digraph G {
    rankdir=LR;
    node [shape=box, style=rounded];

    A [label="Autoencoders"];
    B [label="GANs"];
    C [label="Diffusion Models"];
    D [label="Transformers"];
    E [label="Synthetic Image Generation"];

    A -> E;
    B -> E;
    C -> E;
    D -> E;
}
"""
)

with st.expander("Thesis methodology overview"):
    st.markdown(
        """
1. Extract statistical descriptors from image patches.
2. Measure anomaly signals in texture, frequency, and noise domains.
3. Aggregate local anomalies into a suspicious-region heatmap.
4. Compare feature families in controlled experiments.
"""
    )
